name: Android CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'feature/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Setup Environment Variables for Tests
        env:
          TOUR_API_BASED_URL: ${{ secrets.TOUR_API_BASED_URL }}
          TOUR_API_SERVICE_KEY: ${{ secrets.TOUR_API_SERVICE_KEY  }}
        run: |
          echo TOUR_API_BASED_URL=\"$TOUR_API_BASED_URL\" >> ./local.properties
          echo TOUR_API_SERVICE_KEY=\"$TOUR_API_SERVICE_KEY\" >> ./local.properties

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Create android test report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
